live_config_reload = true

import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"

[window.padding]
x = 5
y = 5

[scrolling]
history = 100000

[font]
size = 18

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Regular"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

